
export interface Part {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  aiHint: string;
  category: 'Pipes & Fittings' | 'Valves' | 'Fixtures' | 'Tools & Sealants' | 'Systems' | 'Specialty' | 'Rare & Obsolete Parts';
}

export const partsData: Part[] = [
  // Pipes & Fittings
  {
    id: 'pvc-elbow-90',
    name: 'PVC 90-Degree Elbow',
    description: 'A standard 1/2 inch PVC elbow for changing pipe direction. Schedule 40.',
    price: 0.89,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pvc elbow',
    category: 'Pipes & Fittings',
  },
  {
    id: 'copper-pipe-10ft',
    name: 'Copper Pipe - 10ft',
    description: 'A 10-foot length of 3/4 inch Type L copper pipe for water supply lines.',
    price: 34.5,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'copper pipe',
    category: 'Pipes & Fittings',
  },
  {
    id: 'pex-tubing-blue-100ft',
    name: 'PEX Tubing, Blue - 100ft',
    description: '100-foot coil of 1/2 inch blue PEX tubing for cold water lines. Flexible and durable.',
    price: 45.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pex tubing',
    category: 'Pipes & Fittings',
  },
    {
    id: 'pex-tubing-red-100ft',
    name: 'PEX Tubing, Red - 100ft',
    description: '100-foot coil of 1/2 inch red PEX tubing for hot water lines. Flexible and durable.',
    price: 45.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pex tubing',
    category: 'Pipes & Fittings',
  },
  {
    id: 'braided-supply-line',
    name: 'Braided Faucet Supply Line',
    description: '20-inch stainless steel braided supply line with 3/8" comp x 1/2" FIP fittings.',
    price: 7.49,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'braided hose',
    category: 'Pipes & Fittings',
  },
  {
    id: 'p-trap-1-1-2',
    name: '1-1/2" P-Trap Assembly',
    description: 'Polypropylene P-trap kit for kitchen or bathroom sinks. Includes all nuts and washers.',
    price: 6.25,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'p trap',
    category: 'Pipes & Fittings',
  },
  {
    id: 'galvanized-nipple-6in',
    name: 'Galvanized Nipple, 3/4" x 6"',
    description: 'A 6-inch long, 3/4 inch diameter galvanized steel nipple for water and gas applications.',
    price: 4.29,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'galvanized pipe',
    category: 'Pipes & Fittings',
  },
  {
    id: 'push-to-connect-coupling',
    name: '1/2" Push-to-Connect Coupling',
    description: 'Brass push-fit coupling for copper, PEX, and CPVC. No soldering required.',
    price: 8.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'push coupling',
    category: 'Pipes & Fittings',
  },
  {
    id: 'abs-tee-4in',
    name: '4" ABS DWV Tee',
    description: '4-inch ABS tee for drain, waste, and vent applications. Hub x Hub x Hub.',
    price: 5.49,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'abs tee',
    category: 'Pipes & Fittings',
  },
  {
    id: 'cpvc-adapter-1/2',
    name: '1/2" CPVC Male Adapter',
    description: 'CPVC male adapter, socket x MIPT. For hot and cold water distribution.',
    price: 1.29,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'cpvc adapter',
    category: 'Pipes & Fittings',
  },
  {
    id: 'dielectric-union-3-4',
    name: '3/4" Dielectric Union',
    description: 'Used to join pipes made from dissimilar metals to prevent corrosion. FIP x Solder.',
    price: 11.79,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'dielectric union',
    category: 'Pipes & Fittings',
  },
  {
    id: 'flexible-gas-connector',
    name: 'Flexible Gas Connector',
    description: '48" stainless steel connector for gas ranges and dryers. 1/2" FIP x 1/2" FIP.',
    price: 28.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'gas hose',
    category: 'Pipes & Fittings',
  },
  {
    id: 'cast-iron-hubless-coupling',
    name: '3" Cast Iron Hubless Coupling',
    description: 'Heavy-duty shielded coupling for joining no-hub cast iron soil pipe.',
    price: 14.25,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'iron coupling',
    category: 'Pipes & Fittings',
  },
  {
    id: 'pvc-cleanout',
    name: '4" PVC Cleanout with Plug',
    description: 'Schedule 40 PVC cleanout adapter and threaded plug for drain line access.',
    price: 7.89,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pvc cleanout',
    category: 'Pipes & Fittings',
  },
  {
    id: 'pipe-hanger-j-hook',
    name: 'PEX J-Hook Pipe Hanger',
    description: 'Nylon J-Hook for supporting 1/2" or 3/4" PEX tubing runs.',
    price: 0.45,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pipe hanger',
    category: 'Pipes & Fittings',
  },
  {
    id: 'reducer-bushing-pvc',
    name: 'PVC Reducer Bushing 1" to 1/2"',
    description: 'Schedule 40 PVC reducer bushing, 1" Spigot x 1/2" Socket.',
    price: 1.19,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pvc reducer',
    category: 'Pipes & Fittings',
  },
  {
    id: 'black-iron-pipe-24in',
    name: 'Black Iron Pipe, 1/2" x 24"',
    description: 'Schedule 40 black iron pipe for gas and air applications.',
    price: 12.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'iron pipe',
    category: 'Pipes & Fittings',
  },
  {
    id: 'fernco-coupling-4in',
    name: '4" Flexible Coupling',
    description: 'Flexible PVC coupling for connecting dissimilar pipes. Stainless steel clamps.',
    price: 9.75,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'flexible coupling',
    category: 'Pipes & Fittings',
  },


  // Valves
  {
    id: 'ball-valve-1/2',
    name: '1/2" Brass Ball Valve',
    description: 'Full-port brass ball valve with a lever handle for shut-off applications.',
    price: 12.75,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'ball valve',
    category: 'Valves',
  },
  {
    id: 'gate-valve-3-4',
    name: '3/4" Gate Valve',
    description: 'Brass gate valve for on/off control without pressure drop. Not for throttling.',
    price: 18.50,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'gate valve',
    category: 'Valves',
  },
  {
    id: 'angle-stop-valve',
    name: '1/2" x 3/8" Angle Stop Valve',
    description: 'Chrome-plated angle stop valve for toilets and faucets. Quarter-turn operation.',
    price: 9.80,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'angle stop',
    category: 'Valves',
  },
  {
    id: 'check-valve-1',
    name: '1" Swing Check Valve',
    description: 'PVC swing check valve to prevent backflow in sump pump and sewage applications.',
    price: 22.15,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'check valve',
    category: 'Valves',
  },
    {
    id: 'inline-check-valve-spring',
    name: '1/2" Spring-Loaded Inline Check Valve',
    description: 'Brass inline check valve with stainless steel spring. Prevents backflow.',
    price: 14.50,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'check valve',
    category: 'Valves',
  },
  {
    id: 'pressure-reducing-valve',
    name: '3/4" Pressure Reducing Valve',
    description: 'Adjustable water pressure regulator for domestic water systems. Factory set at 50 psi.',
    price: 65.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pressure valve',
    category: 'Valves',
  },
  {
    id: 'thermostatic-mixing-valve',
    name: 'Thermostatic Mixing Valve',
    description: '1/2" Lead-free brass TMV. Mixes hot and cold water to deliver tempered water.',
    price: 85.5,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'mixing valve',
    category: 'Valves',
  },
  {
    id: 'backflow-preventer-1',
    name: '1" Backflow Preventer',
    description: 'Reduced Pressure Zone (RPZ) backflow preventer for high-hazard applications.',
    price: 250.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'backflow preventer',
    category: 'Valves',
  },
  {
    id: 'gas-shutoff-valve',
    name: '1/2" Gas Shutoff Valve',
    description: 'CSA approved brass ball valve for natural gas and propane lines.',
    price: 14.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'gas valve',
    category: 'Valves',
  },
  {
    id: 'boiler-drain-valve',
    name: '3/4" Boiler Drain Valve',
    description: 'Multi-turn boiler drain or sediment faucet with male hose thread outlet.',
    price: 7.95,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'drain valve',
    category: 'Valves',
  },
   {
    id: 'hose-bibb-frost-free',
    name: '12" Frost-Free Sillcock',
    description: 'Anti-siphon, frost-free outdoor faucet for preventing frozen pipes.',
    price: 29.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'hose bibb',
    category: 'Valves',
  },
  {
    id: 't-p-relief-valve',
    name: 'Temperature & Pressure Relief Valve',
    description: '3/4" T&P relief valve for water heaters. 150 PSI, 210°F.',
    price: 18.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'relief valve',
    category: 'Valves',
  },
  {
    id: 'solenoid-valve-12v',
    name: '1/2" 12V DC Solenoid Valve',
    description: 'Normally closed electric solenoid valve for automated water control.',
    price: 26.50,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'solenoid valve',
    category: 'Valves',
  },


  // Fixtures
  {
    id: 'sink-faucet-chrome',
    name: 'Chrome Bathroom Faucet',
    description: 'Modern single-handle chrome faucet for bathroom sinks. Includes drain assembly.',
    price: 89.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'sink faucet',
    category: 'Fixtures',
  },
  {
    id: 'kitchen-faucet-ss',
    name: 'Stainless Steel Kitchen Faucet',
    description: 'Pull-down sprayer kitchen faucet in a brushed stainless steel finish.',
    price: 179.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'kitchen faucet',
    category: 'Fixtures',
  },
  {
    id: 'standard-toilet-kit',
    name: 'Standard Two-Piece Toilet',
    description: '1.6 GPF two-piece toilet kit. Includes tank, bowl, seat, and wax ring.',
    price: 129.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'toilet',
    category: 'Fixtures',
  },
  {
    id: 'shower-head-rain',
    name: 'Rainfall Shower Head',
    description: '8-inch chrome rainfall shower head with high-pressure nozzles.',
    price: 45.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'shower head',
    category: 'Fixtures',
  },
  {
    id: 'garbage-disposal-1/2hp',
    name: '1/2 HP Garbage Disposal',
    description: 'Continuous feed garbage disposal with a powerful 1/2 horsepower motor.',
    price: 110.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'garbage disposal',
    category: 'Fixtures',
  },
  {
    id: 'wall-hung-sink',
    name: 'Wall-Hung Sink',
    description: '24" Vitreous china wall-hung sink with single faucet hole. Requires carrier.',
    price: 155.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'wall sink',
    category: 'Fixtures',
  },
  {
    id: 'floor-drain-3in',
    name: '3" PVC Floor Drain',
    description: 'PVC floor drain with 6" round stainless steel grate.',
    price: 32.5,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'floor drain',
    category: 'Fixtures',
  },
  {
    id: 'urinal-commercial',
    name: 'Commercial Urinal',
    description: 'High-efficiency washout urinal, 0.5 GPF, top spud.',
    price: 215.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'urinal',
    category: 'Fixtures',
  },
  {
    id: 'alcove-bathtub',
    name: 'Alcove Bathtub',
    description: '60" x 30" white acrylic alcove bathtub with right-hand drain.',
    price: 289.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'bathtub',
    category: 'Fixtures',
  },
  {
    id: 'pedestal-sink',
    name: 'Pedestal Bathroom Sink',
    description: 'Classic porcelain pedestal sink. Faucet sold separately.',
    price: 175.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pedestal sink',
    category: 'Fixtures',
  },
  {
    id: 'dual-flush-toilet',
    name: 'Dual Flush Elongated Toilet',
    description: 'Water-saving dual flush (1.0/1.6 GPF) one-piece toilet.',
    price: 299.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'dual flush toilet',
    category: 'Fixtures',
  },
  {
    id: 'kitchen-sink-double',
    name: 'Double Bowl Kitchen Sink',
    description: '33" undermount 50/50 double bowl stainless steel kitchen sink.',
    price: 249.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'kitchen sink',
    category: 'Fixtures',
  },
  {
    id: 'shower-valve-trim',
    name: 'Shower Valve Trim Kit',
    description: 'Brushed nickel shower handle and trim kit. Valve not included.',
    price: 79.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'shower handle',
    category: 'Fixtures',
  },
  {
    id: 'bidet-seat',
    name: 'Electronic Bidet Seat',
    description: 'Elongated bidet toilet seat with heated seat, water, and air dryer.',
    price: 350.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'bidet seat',
    category: 'Fixtures',
  },
  {
    id: 'laundry-tub',
    name: 'Freestanding Laundry Tub',
    description: '20-gallon heavy-duty thermoplastic utility tub with integrated legs.',
    price: 85.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'laundry tub',
    category: 'Fixtures',
  },
  {
    id: 'tub-spout-diverter',
    name: 'Tub Spout with Diverter',
    description: 'Chrome-plated tub spout with front-pull diverter for shower activation.',
    price: 24.95,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'tub spout',
    category: 'Fixtures',
  },
  {
    id: 'toilet-fill-valve',
    name: 'Universal Toilet Fill Valve',
    description: 'Adjustable anti-siphon fill valve for most standard toilets.',
    price: 14.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'toilet fill valve',
    category: 'Fixtures',
  },
  {
    id: 'toilet-flapper-3in',
    name: '3-inch Toilet Flapper',
    description: 'Universal 3-inch flapper for large flush valve toilets. Corrosion resistant.',
    price: 8.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'toilet flapper',
    category: 'Fixtures',
  },


  // Tools & Sealants
  {
    id: 'pipe-thread-sealant',
    name: 'Pipe Thread Sealant',
    description: '50ml tube of non-hardening pipe thread sealant for metal pipes. Withstands high pressure.',
    price: 9.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pipe sealant',
    category: 'Tools & Sealants',
  },
  {
    id: 'teflon-tape',
    name: 'Teflon Tape Roll',
    description: '1/2 inch x 520 inch roll of high-density PTFE thread seal tape.',
    price: 1.49,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'teflon tape',
    category: 'Tools & Sealants',
  },
  {
    id: 'pipe-wrench-14in',
    name: '14" Pipe Wrench',
    description: 'Heavy-duty 14-inch cast iron pipe wrench for gripping and turning pipes.',
    price: 24.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pipe wrench',
    category: 'Tools & Sealants',
  },
  {
    id: 'tubing-cutter',
    name: 'Copper Tubing Cutter',
    description: 'Cuts 1/8" to 1-1/8" copper, brass, and aluminum tubing cleanly.',
    price: 15.79,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'tubing cutter',
    category: 'Tools & Sealants',
  },
  {
    id: 'pvc-primer-purple',
    name: 'Purple PVC Primer',
    description: '8 oz. can of aggressive purple primer for PVC and CPVC pipe and fittings.',
    price: 7.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pvc primer',
    category: 'Tools & Sealants',
  },
  {
    id: 'pvc-cement',
    name: 'PVC Cement',
    description: '8 oz. can of medium-bodied fast-setting PVC cement for all schedules and classes.',
    price: 8.79,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pvc cement',
    category: 'Tools & Sealants',
  },
  {
    id: 'pex-crimping-tool',
    name: 'PEX Crimping Tool',
    description: 'Full-size PEX crimping tool for 1/2" and 3/4" copper crimp rings.',
    price: 59.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'crimping tool',
    category: 'Tools & Sealants',
  },
  {
    id: 'plumbers-putty',
    name: 'Plumber\'s Putty',
    description: '9 oz. container of stain-free plumber\'s putty for setting drains and fixtures.',
    price: 3.49,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'plumbers putty',
    category: 'Tools & Sealants',
  },
  {
    id: 'silicone-sealant-clear',
    name: 'Clear Silicone Sealant',
    description: '10.1 oz tube of waterproof and flexible 100% silicone sealant for kitchens and baths.',
    price: 10.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'silicone tube',
    category: 'Tools & Sealants',
  },
  {
    id: 'closet-auger',
    name: '3-Ft Closet Auger',
    description: 'Drain auger specifically designed for clearing toilet clogs.',
    price: 34.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'drain auger',
    category: 'Tools & Sealants',
  },
  {
    id: 'basin-wrench',
    name: 'Basin Wrench',
    description: 'Telescoping basin wrench for tightening and removing faucet and sink nuts.',
    price: 22.49,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'basin wrench',
    category: 'Tools & Sealants',
  },
  {
    id: 'propane-torch-kit',
    name: 'Propane Torch Kit',
    description: 'Basic torch kit with self-igniting torch head and 14.1 oz propane cylinder.',
    price: 49.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'propane torch',
    category: 'Tools & Sealants',
  },
  {
    id: 'caulking-gun',
    name: 'Dripless Caulking Gun',
    description: '9-inch steel skeleton frame caulking gun with smooth rod.',
    price: 12.49,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'caulking gun',
    category: 'Tools & Sealants',
  },
  {
    id: 'lead-free-solder',
    name: 'Lead-Free Solder Wire',
    description: '1/2 lb. spool of silver-bearing lead-free solid wire solder for potable water.',
    price: 28.95,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'solder wire',
    category: 'Tools & Sealants',
  },

  // Systems
  {
    id: 'pre-plumbed-water-heater-kit',
    name: 'Water Heater Connection Kit',
    description: 'Includes two 18" flexible water heater connectors and a 3/4" ball valve.',
    price: 42.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'water heater',
    category: 'Systems',
  },
  {
    id: 'gas-water-heater-40gal',
    name: '40-Gallon Gas Water Heater',
    description: 'Natural gas water heater with a 40-gallon tank, electronic ignition.',
    price: 499.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'gas heater',
    category: 'Systems',
  },
  {
    id: 'electric-water-heater-50gal',
    name: '50-Gallon Electric Water Heater',
    description: 'Tall electric water heater with dual 4500-watt elements.',
    price: 529.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'electric heater',
    category: 'Systems',
  },
  {
    id: 'sump-pump-system',
    name: '1/3 HP Sump Pump System',
    description: 'Complete sump pump system with submersible pump, check valve, and discharge hose.',
    price: 199.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'sump pump',
    category: 'Systems',
  },
  {
    id: 'under-sink-filtration-system',
    name: 'Under-Sink Water Filtration System',
    description: 'Two-stage system reduces chlorine, lead, and other contaminants. Includes dedicated faucet.',
    price: 149.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'water filter',
    category: 'Systems',
  },
  {
    id: 'tankless-water-heater',
    name: 'Electric Tankless Water Heater',
    description: '240V, 27kW on-demand water heater for whole-house use. Requires professional installation.',
    price: 499.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'tankless heater',
    category: 'Systems',
  },
  {
    id: 'expansion-tank-2gal',
    name: '2.1 Gallon Potable Water Expansion Tank',
    description: 'For use with water heaters to control pressure build-up from thermal expansion.',
    price: 49.95,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'expansion tank',
    category: 'Systems',
  },
  {
    id: 'well-pressure-tank',
    name: '20-Gallon Well Pressure Tank',
    description: 'Pre-charged vertical pressure tank for residential well water systems.',
    price: 220.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pressure tank',
    category: 'Systems',
  },
  {
    id: 'water-softener-system',
    name: 'Whole House Water Softener',
    description: '48,000-grain capacity water softener with digital control head.',
    price: 750.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'water softener',
    category: 'Systems',
  },
  {
    id: 'circulator-pump',
    name: 'Hot Water Recirculating Pump',
    description: 'Bronze circulator pump for instant hot water systems. Saves water and time.',
    price: 280.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'recirculating pump',
    category: 'Systems',
  },
  {
    id: 'sewage-ejector-pump',
    name: '1/2 HP Sewage Ejector Pump',
    description: 'Cast iron pump designed to move sewage from a basement to a septic line.',
    price: 320.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'sewage pump',
    category: 'Systems',
  },
  {
    id: 'radiant-heat-manifold',
    name: '5-Loop Stainless Steel Manifold',
    description: 'Pre-assembled manifold for radiant floor heating systems.',
    price: 210.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'radiant manifold',
    category: 'Systems',
  },

  // Specialty
  {
    id: 'water-hammer-arrestor',
    name: 'Water Hammer Arrestor',
    description: 'AA size, 1/2" MIP connection. Absorbs pressure spikes in water lines.',
    price: 15.29,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'hammer arrestor',
    category: 'Specialty',
  },
  {
    id: 'grease-interceptor-20lb',
    name: '20 lb. Grease Interceptor',
    description: 'Steel grease trap for commercial sinks. 10 GPM flow rate.',
    price: 189.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'grease trap',
    category: 'Specialty',
  },
  {
    id: 'trap-primer-valve',
    name: 'Trap Primer Valve',
    description: '1/2" MIP connection trap primer valve. Automatically maintains trap seal.',
    price: 35.5,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'primer valve',
    category: 'Specialty',
  },
  {
    id: 'air-admittance-valve',
    name: 'Air Admittance Valve',
    description: '1-1/2" x 2" mechanical vent for stacks or branches. DFU capacity varies.',
    price: 25.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'air valve',
    category: 'Specialty',
  },
  {
    id: 'saddle-valve',
    name: 'Self-Piercing Saddle Valve',
    description: 'For tapping into existing copper lines to supply humidifiers or ice makers.',
    price: 6.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'saddle valve',
    category: 'Specialty',
  },
  {
    id: 'pipe-insulation-foam',
    name: 'Foam Pipe Insulation',
    description: '6 ft length of self-sealing foam insulation for 3/4" copper pipe.',
    price: 4.29,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'pipe insulation',
    category: 'Specialty',
  },
  {
    id: 'leak-detection-dye',
    name: 'Toilet Tank Leak Detection Dye Tablets',
    description: 'Tablets to safely detect silent leaks in toilet tanks. 2 tablets per pack.',
    price: 2.99,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'dye tablets',
    category: 'Specialty',
  },
  {
    id: 'escutcheon-plate',
    name: '1/2" Split Escutcheon Plate',
    description: 'Chrome-plated hinged flange to conceal pipe penetrations in walls or floors.',
    price: 3.89,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'escutcheon plate',
    category: 'Specialty',
  },
  {
    id: 'fire-sprinkler-head',
    name: 'Pendent Fire Sprinkler Head',
    description: 'Standard coverage, 155°F temperature rating, 1/2" NPT.',
    price: 12.50,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'sprinkler head',
    category: 'Specialty',
  },
  {
    id: 'backwater-valve',
    name: '4" PVC Backwater Valve',
    description: 'Prevents sewage from backing up into a building. Installs on main drain line.',
    price: 75.00,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'backwater valve',
    category: 'Specialty',
  },

  // Rare & Obsolete Parts
  {
    id: 'lead-bend',
    name: '4" Lead Closet Bend',
    description: 'A lead bend for connecting a toilet to a cast iron soil pipe. Requires skilled installation.',
    price: 95.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'lead pipe',
    category: 'Rare & Obsolete Parts',
  },
  {
    id: 'drum-trap',
    name: '1-1/2" Brass Drum Trap',
    description: 'A cylindrical trap used in older plumbing systems, typically for bathtubs. Not for new installs.',
    price: 125.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'brass trap',
    category: 'Rare & Obsolete Parts',
  },
  {
    id: 'wiped-joint-tools',
    name: 'Wiping Cloth & Ladle',
    description: 'Specialized tools for creating a "wiped" solder joint on lead pipes.',
    price: 75.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'metal tools',
    category: 'Rare & Obsolete Parts',
  },
  {
    id: 'oakum',
    name: 'Oakum Rope',
    description: 'Tar-impregnated hemp or jute fiber used for packing cast iron pipe joints before pouring lead.',
    price: 22.5,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'tar rope',
    category: 'Rare & Obsolete Parts',
  },
  {
    id: 'cast-iron-hub',
    name: '4" Cast Iron Soil Pipe Hub',
    description: 'A section of cast iron pipe with a bell-shaped hub for lead and oakum joints.',
    price: 48.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'iron pipe',
    category: 'Rare & Obsolete Parts',
  },
  {
    id: 'faucet-valve-seat',
    name: 'Crane Dial-ese Faucet Valve Seat',
    description: 'Replacement valve seat for vintage Crane faucets. Hard to find part.',
    price: 28.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'faucet seat',
    category: 'Rare & Obsolete Parts',
  },
  {
    id: 'high-tank-toilet-parts',
    name: 'High-Tank Toilet Flush Pipe Kit',
    description: 'Chrome-plated brass flush pipe and fittings for high-tank pull-chain toilets.',
    price: 195.0,
    imageUrl: 'https://placehold.co/64x64.png',
    aiHint: 'toilet parts',
    category: 'Rare & Obsolete Parts',
  },
];
