
export interface Part {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  aiHint: string;
  category: 'Pipes & Fittings' | 'Valves' | 'Fixtures' | 'Tools & Sealants' | 'Systems' | 'Specialty';
}

export const partsData: Part[] = [
  // Pipes & Fittings
  {
    id: 'pvc-elbow-90',
    name: 'PVC 90-Degree Elbow',
    description: 'A standard 1/2 inch PVC elbow for changing pipe direction. Schedule 40.',
    price: 0.89,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pvc elbow',
    category: 'Pipes & Fittings',
  },
  {
    id: 'copper-pipe-10ft',
    name: 'Copper Pipe - 10ft',
    description: 'A 10-foot length of 3/4 inch Type L copper pipe for water supply lines.',
    price: 34.5,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'copper pipe',
    category: 'Pipes & Fittings',
  },
  {
    id: 'pex-tubing-blue-100ft',
    name: 'PEX Tubing, Blue - 100ft',
    description: '100-foot coil of 1/2 inch blue PEX tubing for cold water lines. Flexible and durable.',
    price: 45.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pex tubing',
    category: 'Pipes & Fittings',
  },
  {
    id: 'braided-supply-line',
    name: 'Braided Faucet Supply Line',
    description: '20-inch stainless steel braided supply line with 3/8" comp x 1/2" FIP fittings.',
    price: 7.49,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'braided hose',
    category: 'Pipes & Fittings',
  },
  {
    id: 'p-trap-1-1-2',
    name: '1-1/2" P-Trap Assembly',
    description: 'Polypropylene P-trap kit for kitchen or bathroom sinks. Includes all nuts and washers.',
    price: 6.25,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'p trap',
    category: 'Pipes & Fittings',
  },
  {
    id: 'galvanized-nipple-6in',
    name: 'Galvanized Nipple, 3/4" x 6"',
    description: 'A 6-inch long, 3/4 inch diameter galvanized steel nipple for water and gas applications.',
    price: 4.29,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'galvanized pipe',
    category: 'Pipes & Fittings',
  },
  {
    id: 'push-to-connect-coupling',
    name: '1/2" Push-to-Connect Coupling',
    description: 'Brass push-fit coupling for copper, PEX, and CPVC. No soldering required.',
    price: 8.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'push coupling',
    category: 'Pipes & Fittings',
  },
  {
    id: 'abs-tee-4in',
    name: '4" ABS DWV Tee',
    description: '4-inch ABS tee for drain, waste, and vent applications. Hub x Hub x Hub.',
    price: 5.49,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'abs tee',
    category: 'Pipes & Fittings',
  },
  {
    id: 'cpvc-adapter-1/2',
    name: '1/2" CPVC Male Adapter',
    description: 'CPVC male adapter, socket x MIPT. For hot and cold water distribution.',
    price: 1.29,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'cpvc adapter',
    category: 'Pipes & Fittings',
  },
  {
    id: 'dielectric-union-3-4',
    name: '3/4" Dielectric Union',
    description: 'Used to join pipes made from dissimilar metals to prevent corrosion. FIP x Solder.',
    price: 11.79,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'dielectric union',
    category: 'Pipes & Fittings',
  },
  {
    id: 'flexible-gas-connector',
    name: 'Flexible Gas Connector',
    description: '48" stainless steel connector for gas ranges and dryers. 1/2" FIP x 1/2" FIP.',
    price: 28.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'gas hose',
    category: 'Pipes & Fittings',
  },
  {
    id: 'cast-iron-hubless-coupling',
    name: '3" Cast Iron Hubless Coupling',
    description: 'Heavy-duty shielded coupling for joining no-hub cast iron soil pipe.',
    price: 14.25,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'iron coupling',
    category: 'Pipes & Fittings',
  },
  {
    id: 'pvc-cleanout',
    name: '4" PVC Cleanout with Plug',
    description: 'Schedule 40 PVC cleanout adapter and threaded plug for drain line access.',
    price: 7.89,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pvc cleanout',
    category: 'Pipes & Fittings',
  },

  // Valves
  {
    id: 'ball-valve-1/2',
    name: '1/2" Brass Ball Valve',
    description: 'Full-port brass ball valve with a lever handle for shut-off applications.',
    price: 12.75,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'ball valve',
    category: 'Valves',
  },
  {
    id: 'gate-valve-3-4',
    name: '3/4" Gate Valve',
    description: 'Brass gate valve for on/off control without pressure drop. Not for throttling.',
    price: 18.50,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'gate valve',
    category: 'Valves',
  },
  {
    id: 'angle-stop-valve',
    name: '1/2" x 3/8" Angle Stop Valve',
    description: 'Chrome-plated angle stop valve for toilets and faucets. Quarter-turn operation.',
    price: 9.80,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'angle stop',
    category: 'Valves',
  },
  {
    id: 'check-valve-1',
    name: '1" Swing Check Valve',
    description: 'PVC swing check valve to prevent backflow in sump pump and sewage applications.',
    price: 22.15,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'check valve',
    category: 'Valves',
  },
  {
    id: 'pressure-reducing-valve',
    name: '3/4" Pressure Reducing Valve',
    description: 'Adjustable water pressure regulator for domestic water systems. Factory set at 50 psi.',
    price: 65.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pressure valve',
    category: 'Valves',
  },
  {
    id: 'thermostatic-mixing-valve',
    name: 'Thermostatic Mixing Valve',
    description: '1/2" Lead-free brass TMV. Mixes hot and cold water to deliver tempered water.',
    price: 85.5,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'mixing valve',
    category: 'Valves',
  },
  {
    id: 'backflow-preventer-1',
    name: '1" Backflow Preventer',
    description: 'Reduced Pressure Zone (RPZ) backflow preventer for high-hazard applications.',
    price: 250.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'backflow preventer',
    category: 'Valves',
  },
  {
    id: 'gas-shutoff-valve',
    name: '1/2" Gas Shutoff Valve',
    description: 'CSA approved brass ball valve for natural gas and propane lines.',
    price: 14.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'gas valve',
    category: 'Valves',
  },
  {
    id: 'boiler-drain-valve',
    name: '3/4" Boiler Drain Valve',
    description: 'Multi-turn boiler drain or sediment faucet with male hose thread outlet.',
    price: 7.95,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'drain valve',
    category: 'Valves',
  },

  // Fixtures
  {
    id: 'sink-faucet-chrome',
    name: 'Chrome Bathroom Faucet',
    description: 'Modern single-handle chrome faucet for bathroom sinks. Includes drain assembly.',
    price: 89.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'sink faucet',
    category: 'Fixtures',
  },
  {
    id: 'kitchen-faucet-ss',
    name: 'Stainless Steel Kitchen Faucet',
    description: 'Pull-down sprayer kitchen faucet in a brushed stainless steel finish.',
    price: 179.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'kitchen faucet',
    category: 'Fixtures',
  },
  {
    id: 'standard-toilet-kit',
    name: 'Standard Two-Piece Toilet',
    description: '1.6 GPF two-piece toilet kit. Includes tank, bowl, seat, and wax ring.',
    price: 129.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'toilet',
    category: 'Fixtures',
  },
  {
    id: 'shower-head-rain',
    name: 'Rainfall Shower Head',
    description: '8-inch chrome rainfall shower head with high-pressure nozzles.',
    price: 45.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'shower head',
    category: 'Fixtures',
  },
  {
    id: 'garbage-disposal-1/2hp',
    name: '1/2 HP Garbage Disposal',
    description: 'Continuous feed garbage disposal with a powerful 1/2 horsepower motor.',
    price: 110.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'garbage disposal',
    category: 'Fixtures',
  },
  {
    id: 'wall-hung-sink',
    name: 'Wall-Hung Sink',
    description: '24" Vitreous china wall-hung sink with single faucet hole. Requires carrier.',
    price: 155.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'wall sink',
    category: 'Fixtures',
  },
  {
    id: 'floor-drain-3in',
    name: '3" PVC Floor Drain',
    description: 'PVC floor drain with 6" round stainless steel grate.',
    price: 32.5,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'floor drain',
    category: 'Fixtures',
  },
  {
    id: 'urinal-commercial',
    name: 'Commercial Urinal',
    description: 'High-efficiency washout urinal, 0.5 GPF, top spud.',
    price: 215.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'urinal',
    category: 'Fixtures',
  },
  {
    id: 'alcove-bathtub',
    name: 'Alcove Bathtub',
    description: '60" x 30" white acrylic alcove bathtub with right-hand drain.',
    price: 289.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'bathtub',
    category: 'Fixtures',
  },
  {
    id: 'pedestal-sink',
    name: 'Pedestal Bathroom Sink',
    description: 'Classic porcelain pedestal sink. Faucet sold separately.',
    price: 175.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pedestal sink',
    category: 'Fixtures',
  },
  {
    id: 'dual-flush-toilet',
    name: 'Dual Flush Elongated Toilet',
    description: 'Water-saving dual flush (1.0/1.6 GPF) one-piece toilet.',
    price: 299.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'dual flush toilet',
    category: 'Fixtures',
  },
  {
    id: 'kitchen-sink-double',
    name: 'Double Bowl Kitchen Sink',
    description: '33" undermount 50/50 double bowl stainless steel kitchen sink.',
    price: 249.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'kitchen sink',
    category: 'Fixtures',
  },
  {
    id: 'shower-valve-trim',
    name: 'Shower Valve Trim Kit',
    description: 'Brushed nickel shower handle and trim kit. Valve not included.',
    price: 79.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'shower handle',
    category: 'Fixtures',
  },
  {
    id: 'bidet-seat',
    name: 'Electronic Bidet Seat',
    description: 'Elongated bidet toilet seat with heated seat, water, and air dryer.',
    price: 350.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'bidet seat',
    category: 'Fixtures',
  },


  // Tools & Sealants
  {
    id: 'pipe-thread-sealant',
    name: 'Pipe Thread Sealant',
    description: '50ml tube of non-hardening pipe thread sealant for metal pipes. Withstands high pressure.',
    price: 9.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pipe sealant',
    category: 'Tools & Sealants',
  },
  {
    id: 'teflon-tape',
    name: 'Teflon Tape Roll',
    description: '1/2 inch x 520 inch roll of high-density PTFE thread seal tape.',
    price: 1.49,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'teflon tape',
    category: 'Tools & Sealants',
  },
  {
    id: 'pipe-wrench-14in',
    name: '14" Pipe Wrench',
    description: 'Heavy-duty 14-inch cast iron pipe wrench for gripping and turning pipes.',
    price: 24.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pipe wrench',
    category: 'Tools & Sealants',
  },
  {
    id: 'tubing-cutter',
    name: 'Copper Tubing Cutter',
    description: 'Cuts 1/8" to 1-1/8" copper, brass, and aluminum tubing cleanly.',
    price: 15.79,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'tubing cutter',
    category: 'Tools & Sealants',
  },
  {
    id: 'pvc-cement',
    name: 'PVC Cement',
    description: '8 oz. can of medium-bodied fast-setting PVC cement for all schedules and classes.',
    price: 8.79,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pvc cement',
    category: 'Tools & Sealants',
  },
  {
    id: 'pex-crimping-tool',
    name: 'PEX Crimping Tool',
    description: 'Full-size PEX crimping tool for 1/2" and 3/4" copper crimp rings.',
    price: 59.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'crimping tool',
    category: 'Tools & Sealants',
  },
  {
    id: 'plumbers-putty',
    name: 'Plumber\'s Putty',
    description: '9 oz. container of stain-free plumber\'s putty for setting drains and fixtures.',
    price: 3.49,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'plumbers putty',
    category: 'Tools & Sealants',
  },
  {
    id: 'closet-auger',
    name: '3-Ft Closet Auger',
    description: 'Drain auger specifically designed for clearing toilet clogs.',
    price: 34.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'drain auger',
    category: 'Tools & Sealants',
  },

  // Systems
  {
    id: 'pre-plumbed-water-heater-kit',
    name: 'Water Heater Connection Kit',
    description: 'Includes two 18" flexible water heater connectors and a 3/4" ball valve.',
    price: 42.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'water heater',
    category: 'Systems',
  },
  {
    id: 'sump-pump-system',
    name: '1/3 HP Sump Pump System',
    description: 'Complete sump pump system with submersible pump, check valve, and discharge hose.',
    price: 199.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'sump pump',
    category: 'Systems',
  },
  {
    id: 'under-sink-filtration-system',
    name: 'Under-Sink Water Filtration System',
    description: 'Two-stage system reduces chlorine, lead, and other contaminants. Includes dedicated faucet.',
    price: 149.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'water filter',
    category: 'Systems',
  },
  {
    id: 'tankless-water-heater',
    name: 'Electric Tankless Water Heater',
    description: '240V, 27kW on-demand water heater for whole-house use. Requires professional installation.',
    price: 499.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'tankless heater',
    category: 'Systems',
  },
  {
    id: 'expansion-tank-2gal',
    name: '2.1 Gallon Potable Water Expansion Tank',
    description: 'For use with water heaters to control pressure build-up from thermal expansion.',
    price: 49.95,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'expansion tank',
    category: 'Systems',
  },
  {
    id: 'well-pressure-tank',
    name: '20-Gallon Well Pressure Tank',
    description: 'Pre-charged vertical pressure tank for residential well water systems.',
    price: 220.00,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pressure tank',
    category: 'Systems',
  },

  // Specialty
  {
    id: 'water-hammer-arrestor',
    name: 'Water Hammer Arrestor',
    description: 'AA size, 1/2" MIP connection. Absorbs pressure spikes in water lines.',
    price: 15.29,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'hammer arrestor',
    category: 'Specialty',
  },
  {
    id: 'grease-interceptor-20lb',
    name: '20 lb. Grease Interceptor',
    description: 'Steel grease trap for commercial sinks. 10 GPM flow rate.',
    price: 189.0,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'grease trap',
    category: 'Specialty',
  },
  {
    id: 'trap-primer-valve',
    name: 'Trap Primer Valve',
    description: '1/2" MIP connection trap primer valve. Automatically maintains trap seal.',
    price: 35.5,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'primer valve',
    category: 'Specialty',
  },
  {
    id: 'air-admittance-valve',
    name: 'Air Admittance Valve',
    description: '1-1/2" x 2" mechanical vent for stacks or branches. DFU capacity varies.',
    price: 25.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'air valve',
    category: 'Specialty',
  },
  {
    id: 'saddle-valve',
    name: 'Self-Piercing Saddle Valve',
    description: 'For tapping into existing copper lines to supply humidifiers or ice makers.',
    price: 6.99,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'saddle valve',
    category: 'Specialty',
  },
];
